version: '3'


networks:
    mysql-phpmyadmin:
        name: mysql-phpmyadmin
        driver: bridge

volumes:
    mysqldata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '${HOME}/Documents/test/mysql-phpmyadmin/data'

services:
    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: shoolapi_db
            MYSQL_USER: user
            MYSQL_PASSWORD: 123
        ports:
            - "6033:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
          mysql-phpmyadmin:
           aliases:
              - mysql


    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8081:80
        networks:
          mysql-phpmyadmin:
               aliases:
                 - phpmyadmin      
                